package com.techvision.aipos.entity.preset

import com.techvision.aipos.R
import java.util.*

class PresetItem(var uiName: String, var ids: Int) {
    companion object {
        val itemHashMap: HashMap<String, PresetItem> = object : HashMap<String, PresetItem>() {
            init {
                put("baicai", PresetItem("白菜", R.drawable.ic_baicai))
                put("bailuobo", PresetItem("白萝卜", R.drawable.ic_bailuobo))
                put("baimigua", PresetItem("白蜜瓜", R.drawable.ic_baimigua))
                put("baixinhuolongguo", PresetItem("白心火龙果", R.drawable.ic_baixinhuolongguo))
                put("banli", PresetItem("板栗", R.drawable.ic_banli))
                put("banlinangua", PresetItem("板栗南瓜", R.drawable.ic_banlinangua))
                put("baocai", PresetItem("包菜", R.drawable.ic_baocai))
                put("beibeinangua", PresetItem("贝贝南瓜", R.drawable.ic_beibeinangua))
                put("biandou", PresetItem("扁豆", R.drawable.ic_biandou))
                put("binchuanhongti", PresetItem("宾川红提", R.drawable.ic_binchuanhongti))
                put("bocai", PresetItem("菠菜", R.drawable.ic_bocai))
                put("boluo", PresetItem("菠萝", R.drawable.ic_boluo))

                put("caitai", PresetItem("菜苔", R.drawable.ic_caitai))
                put("cancai", PresetItem("蚕菜", R.drawable.ic_cancai))
                put("caomei", PresetItem("草莓", R.drawable.ic_caomei))
                put("changbaicai", PresetItem("长白菜", R.drawable.ic_changbaicai))
                put("chelizi", PresetItem("车厘子", R.drawable.ic_chelizi))
                put("chengzi", PresetItem("橙子", R.drawable.ic_chengzi))
                put("chuncai", PresetItem("春菜", R.drawable.ic_chuncai))
                put("cihuanggua", PresetItem("刺黄瓜", R.drawable.ic_cihuanggua))

                put("dabaicai", PresetItem("大白菜", R.drawable.ic_dabaicai))
                put("dacong", PresetItem("大葱", R.drawable.ic_dacong))
                put("dasuan", PresetItem("大蒜", R.drawable.ic_dasuan))
                put("dayekongxincai", PresetItem("大叶空心菜", R.drawable.ic_dayekongxincai))
                put("dayutou", PresetItem("大芋头", R.drawable.ic_dayutou))
                put("digua", PresetItem("地瓜", R.drawable.ic_digua))
                put("donggua", PresetItem("冬瓜", R.drawable.ic_donggua))
                put("doujiao", PresetItem("豆角", R.drawable.ic_doujiao))
                put("douya", PresetItem("豆芽", R.drawable.ic_douya))
                
                put("fenjiao", PresetItem("粉蕉", R.drawable.ic_fenjiao))
                put("foshouguamiao", PresetItem("佛手瓜苗", R.drawable.ic_foshouguamiao))
                put("gouqiye", PresetItem("枸杞叶", R.drawable.ic_gouqiye))
                put("guangdongcaixin", PresetItem("广东菜心", R.drawable.ic_guangdongcaixin))

                put("hamigua", PresetItem("哈密瓜", R.drawable.ic_hamigua))
                put("hanhuanggua", PresetItem("旱黄瓜", R.drawable.ic_hanhuanggua))
                put("heibulin", PresetItem("黑布林", R.drawable.ic_heibulin))
                put("helandou", PresetItem("荷兰豆", R.drawable.ic_helandou))
                put("hongcongtou", PresetItem("红葱头", R.drawable.ic_hongcongtou))
                put("hongdenglongjiao", PresetItem("红灯笼椒", R.drawable.ic_hongdenglongjiao))
                put("hongfushi", PresetItem("红富士", R.drawable.ic_hongfushi))
                put("honghangjiao", PresetItem("红杭椒", R.drawable.ic_honghangjiao))
                put("hongpali", PresetItem("红杷梨", R.drawable.ic_hongpali))
                put("hongshu", PresetItem("红薯", R.drawable.ic_hongshu))
                put("hongshuteng", PresetItem("红薯藤", R.drawable.ic_hongshuteng))
                put("hongti", PresetItem("红提", R.drawable.ic_hongti))
                put("hongxinhuolongguo", PresetItem("红心火龙果", R.drawable.ic_hongxinhuolongguo))
                put("huangpili", PresetItem("黄皮梨", R.drawable.ic_huangpili))
                put("huangyuanshuai", PresetItem("黄元帅", R.drawable.ic_huangyuanshuai))
                put("huayecai", PresetItem("花椰菜", R.drawable.ic_huayecai))
                put("huluobo", PresetItem("胡萝卜", R.drawable.ic_huluobo))

                put("jiaobai", PresetItem("茭白", R.drawable.ic_jiaobai))
                put("jiaogua", PresetItem("角瓜", R.drawable.ic_jiaogua))
                put("jiecai", PresetItem("芥菜", R.drawable.ic_jiecai))
                put("jielan", PresetItem("芥兰", R.drawable.ic_jielan))
                put("jinzhengu", PresetItem("金针菇", R.drawable.ic_jinzhengu))
                put("jiucai", PresetItem("韭菜", R.drawable.ic_jiucai))
                put("jiucaihua", PresetItem("韭菜花", R.drawable.ic_jiucaihua))
                put("jiuhuang", PresetItem("韭黄", R.drawable.ic_jiuhuang))
                put("jufengputao", PresetItem("巨峰葡萄", R.drawable.ic_jufengputao))

                put("kongxincaigan", PresetItem("空心菜杆", R.drawable.ic_kongxincaigan))
                put("kugua", PresetItem("苦瓜", R.drawable.ic_kugua))
                put("kumaicai", PresetItem("苦麦菜", R.drawable.ic_kumaicai))

                put("lanmei", PresetItem("蓝莓", R.drawable.ic_lanmei))
                put("laoyezi", PresetItem("老椰子", R.drawable.ic_laoyezi))
                put("lianou", PresetItem("莲藕", R.drawable.ic_lianou))
                put("lianpeng", PresetItem("莲蓬", R.drawable.ic_lianpeng))
                put("lianwu", PresetItem("莲雾", R.drawable.ic_lianwu))
                put("liulian", PresetItem("榴莲", R.drawable.ic_liulian))
                put("lizhi", PresetItem("荔枝", R.drawable.ic_lizhi))
                put("longyan", PresetItem("龙眼", R.drawable.ic_longyan))
                put("luosijiao", PresetItem("螺丝椒", R.drawable.ic_luosijiao))

                put("maodonggua", PresetItem("毛冬瓜", R.drawable.ic_maodonggua))
                put("maodou", PresetItem("毛豆", R.drawable.ic_maodou))
                put("mihoutao", PresetItem("猕猴桃", R.drawable.ic_mihoutao))
                put("naibaicai", PresetItem("奶白菜", R.drawable.ic_naibaicai))
                put("nanfeigan", PresetItem("南非柑", R.drawable.ic_nanfeigan))
                put("nanguaxu", PresetItem("南瓜须", R.drawable.ic_nanguaxu))
                put("ningmeng", PresetItem("柠檬", R.drawable.ic_ningmeng))
                put("niuyouguo", PresetItem("牛油果", R.drawable.ic_niuyouguo))

                put("pinggu", PresetItem("平菇", R.drawable.ic_pinggu))
                put("pipa", PresetItem("枇杷", R.drawable.ic_pipa))
                put("qianhuipili", PresetItem("浅灰皮梨", R.drawable.ic_qianhuipili))
                put("qiaotou", PresetItem("荞头", R.drawable.ic_qiaotou))
                put("qicaijiao", PresetItem("七彩椒", R.drawable.ic_qicaijiao))
                put("qiezi", PresetItem("茄子", R.drawable.ic_qiezi))
                put("qilingua", PresetItem("麒麟瓜", R.drawable.ic_qilingua))
                put("qincai", PresetItem("芹菜", R.drawable.ic_qincai))
                put("qingdenglongjiao", PresetItem("青灯笼椒", R.drawable.ic_qingdenglongjiao))
                put("qinghangjiao", PresetItem("青杭椒", R.drawable.ic_qinghangjiao))
                put("qingli", PresetItem("青李", R.drawable.ic_qingli))
                put("qingningmeng", PresetItem("青柠檬", R.drawable.ic_qingningmeng))
                put("qingpimugua", PresetItem("青皮木瓜", R.drawable.ic_qingpimugua))
                put("qingpingguo", PresetItem("青苹果", R.drawable.ic_qingpingguo))
                put("qingyezi", PresetItem("青椰子", R.drawable.ic_qingyezi))
                put("qiukui", PresetItem("秋葵", R.drawable.ic_qiukui))

                put("renshengguo", PresetItem("人参果", R.drawable.ic_renshengguo))
                put("roujiecai", PresetItem("肉芥菜", R.drawable.ic_roujiecai))
                put("sanhuali", PresetItem("三华李", R.drawable.ic_sanhuali))
                put("shanghaiqing", PresetItem("上海青", R.drawable.ic_shanghaiqing))
                put("shanyao", PresetItem("山药", R.drawable.ic_shanyao))
                put("shanzhu", PresetItem("山竹", R.drawable.ic_shanzhu))
                put("sheguo", PresetItem("蛇果", R.drawable.ic_sheguo))
                put("shengcai", PresetItem("生菜", R.drawable.ic_shengcai))
                put("shengjiang", PresetItem("生姜", R.drawable.ic_shengjiang))
                put("shengnvguo", PresetItem("圣女果", R.drawable.ic_shengnvguo))
                put("shijiaguo", PresetItem("释迦果", R.drawable.ic_shijiaguo))
                put("shuimitao", PresetItem("水蜜桃", R.drawable.ic_shuimitao))
                put("shuixianmang", PresetItem("水仙芒", R.drawable.ic_shuixianmang))
                put("sigua", PresetItem("丝瓜", R.drawable.ic_sigua))
                put("sijidou", PresetItem("四季豆", R.drawable.ic_sijidou))
                put("suantai", PresetItem("蒜薹", R.drawable.ic_suantai))
                put("suantou", PresetItem("蒜头", R.drawable.ic_suantou))

                put("tiandou", PresetItem("甜豆", R.drawable.ic_tiandou))
                put("tianmaicai", PresetItem("甜麦菜", R.drawable.ic_tianmaicai))
                put("tudou", PresetItem("土豆", R.drawable.ic_tudou))
                put("wawacai", PresetItem("娃娃菜", R.drawable.ic_wawacai))
                put("wogan", PresetItem("沃柑", R.drawable.ic_wogan))
                put("woju", PresetItem("莴苣", R.drawable.ic_woju))
                put("wuziputao", PresetItem("无籽葡萄", R.drawable.ic_wuziputao))

                put("xiancai", PresetItem("苋菜", R.drawable.ic_xiancai))
                put("xiangcai", PresetItem("香菜", R.drawable.ic_xiangcai))
                put("xiangcong", PresetItem("香葱", R.drawable.ic_xiangcong))
                put("xianggu", PresetItem("香菇", R.drawable.ic_xianggu))
                put("xiangjiao", PresetItem("香蕉", R.drawable.ic_xiangjiao))
                put("xiangli", PresetItem("香梨", R.drawable.ic_xiangli))
                put("xianweigu", PresetItem("鲜味菇", R.drawable.ic_xianweigu))
                put("xiaobaicai", PresetItem("小白菜", R.drawable.ic_xiaobaicai))
                put("xiaomangguo", PresetItem("小芒果", R.drawable.ic_xiaomangguo))
                put("xiaomila", PresetItem("小米辣", R.drawable.ic_xiaomila))
                put("xiaonangua", PresetItem("小南瓜", R.drawable.ic_xiaonangua))
                put("xiaosijidou", PresetItem("小四季豆", R.drawable.ic_xiaosijidou))
                put("xiaotudou", PresetItem("小土豆", R.drawable.ic_xiaotudou))
                put("xiaoyekongxincai", PresetItem("小叶空心菜", R.drawable.ic_xiaoyekongxincai))
                put("xiaoyutou", PresetItem("小芋头", R.drawable.ic_xiaoyutou))
                put("xihongshi", PresetItem("西红柿", R.drawable.ic_xihongshi))
                put("xihulu", PresetItem("西葫芦", R.drawable.ic_xihulu))
                put("xilanhua", PresetItem("西兰花", R.drawable.ic_xilanhua))
                put("ximei", PresetItem("西梅", R.drawable.ic_ximei))
                put("xinbaogu", PresetItem("杏鲍菇", R.drawable.ic_xinbaogu))
                put("xinlihongluobo", PresetItem("心里红萝卜", R.drawable.ic_xinlihongluobo))
                put("xueli", PresetItem("雪梨", R.drawable.ic_xueli))

                put("yangcong", PresetItem("洋葱", R.drawable.ic_yangcong))
                put("yangmei", PresetItem("杨梅", R.drawable.ic_yangmei))
                put("yangtao", PresetItem("杨桃", R.drawable.ic_yangtao))
                put("yelaixiang", PresetItem("夜来香", R.drawable.ic_yelaixiang))
                put("youjiao", PresetItem("油椒", R.drawable.ic_youjiao))
                put("youmaicai", PresetItem("油麦菜", R.drawable.ic_youmaicai))
                put("youtao", PresetItem("油桃", R.drawable.ic_youtao))
                put("yumi", PresetItem("玉米", R.drawable.ic_yumi))
                put("yuxingcao", PresetItem("鱼腥草", R.drawable.ic_yuxingcao))
                put("ziganlan", PresetItem("紫甘蓝", R.drawable.ic_ziganlan))
                put("zishu", PresetItem("紫薯", R.drawable.ic_zishu))
            }
        }
    }
}
